/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 my_room.glb 
Author: Oleaf (https://sketchfab.com/homkahom0)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/my-room-109790fce06a4ff3b4b96c2c2cfcc33e
Title: My room
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GlowingButton } from "./GlowingButton";

// Tạo trục với chiều dài 5 đơn vị

export function Room(props) {
  const { nodes, materials, scene } = useGLTF("/models/my_room.glb");
  const buttonGeometry = new THREE.BoxGeometry(0.2, 0.1, 0.05);
  const buttonMaterial = new THREE.MeshStandardMaterial({ color: "red" });
  const buttonMesh = new THREE.Mesh(buttonGeometry, buttonMaterial);

  // Đặt vị trí nút trong model
  buttonMesh.position.set(0, 1, 0); // X, Y, Z
  buttonMesh.name = "myButton";
  // const axesHelper = new THREE.AxesHelper(5);
  // scene.add(axesHelper);
  return (
    <group {...props} dispose={null}>
      {/* <axesHelper args={[50]} /> */}
      

      {/* <mesh
        geometry={new THREE.BoxGeometry(0.3, 0.2, 0.1)}
        position={[10, 15, -11.2]}
        onClick={() => console.log("Button clicked!")}
      >
        <meshStandardMaterial
          color="red"
          emissive="red"
          emissiveIntensity={1} // độ sáng
        />
      </mesh> */}
      <mesh
        geometry={nodes.comp_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.table_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.cabin_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_emis_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.body1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/models/my_room.glb");
